# Generated by Django 3.2 on 2021-04-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_on', models.TimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('step', models.CharField(choices=[('one', 'start'), ('two', 'doing'), ('three', 'finish'), ('four', 'history')], default='one', max_length=64)),
            ],
        ),
    ]
