# Generated by Django 3.2 on 2021-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0004_alter_todo_cr_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=2048, null=True)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
