# Generated by Django 3.2 on 2021-04-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0005_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='images',
        ),
    ]
